@startuml
annotation java.lang.Override
class java.io.FileWriter
class java.io.IOException
class java.io.PrintWriter
class java.time.LocalDateTime
class java.time.format.DateTimeFormatter
class java.util.ArrayList
class java.util.List
class utility.Log
class utility.Query
utility.Log ..> java.io.FileWriter
utility.Log ..> java.io.IOException
utility.Log ..> java.io.PrintWriter
utility.Log ..> java.time.LocalDateTime
utility.Log ..> java.time.format.DateTimeFormatter
utility.Query ..> java.lang.Override
utility.Query ..> java.util.ArrayList
utility.Query ..> java.util.List
@enduml