/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.panel;

import control.ProjectControl;
import control.SessionControl;
import javax.swing.JOptionPane;
import model.Project;
import model.User;

/**
 *
 * @author Silvanus
 */
public class AddProjectPanel extends javax.swing.JFrame {
    private SessionControl sessionControl;
    private ProjectControl projectControl;
    private User currentUser;
    
    /**
     * Creates new form AddProjectPanel
     */
    public AddProjectPanel() {
        initComponents();

        currentUser = sessionControl.getCurrentUser();
        projectControl = new ProjectControl();
        projectControl.setUser(currentUser);
    }
    
    // dapat user dari session pada view yg memanggil panel ini
    public AddProjectPanel(User currentUser) {
        initComponents();

        this.currentUser = currentUser;

        this.projectControl = new ProjectControl();
        this.projectControl.setUser(currentUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectNamePanel = new javax.swing.JPanel();
        CardTitleLabel = new javax.swing.JLabel();
        ProjectNameTextField = new javax.swing.JTextField();
        ProjectNameLabel = new javax.swing.JLabel();
        CancelLabel = new javax.swing.JLabel();
        DescPanel = new javax.swing.JPanel();
        DescScrollPane = new javax.swing.JScrollPane();
        DescTextArea = new javax.swing.JTextArea();
        ProjectDescLabel = new javax.swing.JLabel();
        AddProjectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 280));

        CardTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CardTitleLabel.setText("Add Poject");

        ProjectNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectNameTextFieldActionPerformed(evt);
            }
        });

        ProjectNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ProjectNameLabel.setText("Project Name");

        javax.swing.GroupLayout ProjectNamePanelLayout = new javax.swing.GroupLayout(ProjectNamePanel);
        ProjectNamePanel.setLayout(ProjectNamePanelLayout);
        ProjectNamePanelLayout.setHorizontalGroup(
            ProjectNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProjectNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectNameTextField)
                    .addGroup(ProjectNamePanelLayout.createSequentialGroup()
                        .addGroup(ProjectNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CardTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProjectNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProjectNamePanelLayout.setVerticalGroup(
            ProjectNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CardTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProjectNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CancelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/project_panel/x_icon.png"))); // NOI18N
        CancelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelLabelMouseClicked(evt);
            }
        });

        DescTextArea.setColumns(20);
        DescTextArea.setRows(5);
        DescScrollPane.setViewportView(DescTextArea);

        ProjectDescLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ProjectDescLabel.setText("Project Description");

        javax.swing.GroupLayout DescPanelLayout = new javax.swing.GroupLayout(DescPanel);
        DescPanel.setLayout(DescPanelLayout);
        DescPanelLayout.setHorizontalGroup(
            DescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addGroup(DescPanelLayout.createSequentialGroup()
                        .addComponent(ProjectDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DescPanelLayout.setVerticalGroup(
            DescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DescPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DescScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AddProjectButton.setBackground(new java.awt.Color(102, 255, 102));
        AddProjectButton.setText("Add");
        AddProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DescPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProjectNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AddProjectButton)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProjectNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CancelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(DescPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddProjectButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProjectButtonActionPerformed
        String name = ProjectNameTextField.getText().trim();
        String description = DescTextArea.getText().trim();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Project name tidak boleh kosong!");
            return;
        }

        try {
            Project project = new Project();

            project.setName(name);
            project.setDescription(description);

            int result = projectControl.add(project);

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Project berhasil ditambahkan!");

                ProjectNameTextField.setText("");
                DescTextArea.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan project!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddProjectButtonActionPerformed

    private void CancelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelLabelMouseClicked
        dispose();
    }//GEN-LAST:event_CancelLabelMouseClicked

    private void ProjectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProjectNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProjectPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProjectPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProjectPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProjectPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProjectPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProjectButton;
    private javax.swing.JLabel CancelLabel;
    private javax.swing.JLabel CardTitleLabel;
    private javax.swing.JPanel DescPanel;
    private javax.swing.JScrollPane DescScrollPane;
    private javax.swing.JTextArea DescTextArea;
    private javax.swing.JLabel ProjectDescLabel;
    private javax.swing.JLabel ProjectNameLabel;
    private javax.swing.JPanel ProjectNamePanel;
    private javax.swing.JTextField ProjectNameTextField;
    // End of variables declaration//GEN-END:variables
}
