/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import control.ProjectControl;
import control.SessionControl;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Project;

/**
 *
 * @author aldio
 */
import model.Session;
import java.io.File;
import java.awt.Image;
import javax.swing.ImageIcon;
import model.User;

public class HomePagePanel extends javax.swing.JPanel {

    private SessionControl sessionControl = new SessionControl();
    private ProjectControl projectControl = new ProjectControl(sessionControl.getCurrentUser());
    private List<Project> projects = null;
    /**
     * Creates new form HomePagePanel
     */
    private onProfileClickListener profileClickListener;

    public HomePagePanel() {
        System.out.println("MASUK");
        initComponents();
        try {
            projects = projectControl.fetchUserProjects(sessionControl.getCurrentUser());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(ContentPanel, e.getMessage());
        }
        setupFocusClearance();
        addProjects();
        updateProfileIcon(sessionControl.getCurrentUser());
        initKanbanBoard();

    }

    public void updateProfileIcon(User currentUser) {
        if (currentUser != null && currentUser.getProfilePicture() != null && !currentUser.getProfilePicture().isEmpty()) {
            File file = new File(currentUser.getProfilePicture());
            if (file.exists()) {
                ImageIcon icon = new ImageIcon(file.getAbsolutePath());

                icon.getImage().flush();

                Image img = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
                Profile.setIcon(new ImageIcon(img));
                Profile.setText("");

                Profile.revalidate();
                Profile.repaint();
            } else {
                System.out.println("File foto profil tidak ditemukan di: " + file.getAbsolutePath());
            }
        }
    }

    private void addProjects() {
        if (projects == null || projects.isEmpty()) {
            projectPanel.add(new JLabel("no project for this user."));
            return;
        }
        for (Project p : projects) {
            projectPanel.add(new ProjectTab(p));
        }
    }

    private void initKanbanBoard() {
        KanbanCard papanKanban = new KanbanCard();

        Kanban.setLayout(new java.awt.BorderLayout());

        Kanban.add(papanKanban, java.awt.BorderLayout.CENTER);

        Kanban.revalidate();
        Kanban.repaint();
    }

    public void setOnProfileClickListener(onProfileClickListener listener) {
        this.profileClickListener = listener;
    }

    public interface onProfileClickListener {

        void onProfileClick();
    }

    private void setupFocusClearance() {
        MainPanel.setFocusable(true);
        TopBarPanel.setFocusable(true);
        SideBarPanel.setFocusable(true);
        ContentPanel.setFocusable(true);

        java.awt.event.MouseAdapter clearFocusAdapter = new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainPanel.requestFocusInWindow();
            }
        };

        this.addMouseListener(clearFocusAdapter);
        MainPanel.addMouseListener(clearFocusAdapter);
        TopBarPanel.addMouseListener(clearFocusAdapter);
        SideBarPanel.addMouseListener(clearFocusAdapter);
        ContentPanel.addMouseListener(clearFocusAdapter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TopBarPanel = new javax.swing.JPanel();
        SearchTxt = new javax.swing.JTextField();
        Profile = new javax.swing.JLabel();
        SideBarPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        projectPanel = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JTabbedPane();
        Kalender = new javax.swing.JPanel();
        Kanban = new javax.swing.JPanel();
        AddTaskEventButton = new javax.swing.JButton();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        MainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        MainPanel.setVerifyInputWhenFocusTarget(false);

        TopBarPanel.setBackground(new java.awt.Color(204, 0, 51));

        SearchTxt.setText("Cari Kegiatan");
        SearchTxt.setAutoscrolls(false);
        SearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxtActionPerformed(evt);
            }
        });

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashboard_panel/profile.png"))); // NOI18N
        Profile.setToolTipText("");
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TopBarPanelLayout = new javax.swing.GroupLayout(TopBarPanel);
        TopBarPanel.setLayout(TopBarPanelLayout);
        TopBarPanelLayout.setHorizontalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(375, 375, 375)
                .addComponent(Profile)
                .addContainerGap())
        );
        TopBarPanelLayout.setVerticalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchTxt)
                    .addGroup(TopBarPanelLayout.createSequentialGroup()
                        .addComponent(Profile)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        SideBarPanel.setBackground(new java.awt.Color(255, 255, 255));
        SideBarPanel.setMaximumSize(new java.awt.Dimension(32767, 720));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(162, 0, 33));
        jLabel2.setText("+");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(162, 0, 33));
        jLabel1.setText("Proyek");

        projectPanel.setMaximumSize(new java.awt.Dimension(500, 10000));
        projectPanel.setLayout(new javax.swing.BoxLayout(projectPanel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout SideBarPanelLayout = new javax.swing.GroupLayout(SideBarPanel);
        SideBarPanel.setLayout(SideBarPanelLayout);
        SideBarPanelLayout.setHorizontalGroup(
            SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SideBarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        SideBarPanelLayout.setVerticalGroup(
            SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        for(int i= 0; i < 3 ; i++){
            projectPanel.add(new JLabel());
        }

        javax.swing.GroupLayout KalenderLayout = new javax.swing.GroupLayout(Kalender);
        Kalender.setLayout(KalenderLayout);
        KalenderLayout.setHorizontalGroup(
            KalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1078, Short.MAX_VALUE)
        );
        KalenderLayout.setVerticalGroup(
            KalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        ContentPanel.addTab("Tabel", Kalender);

        AddTaskEventButton.setText("tambah");
        AddTaskEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskEventButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KanbanLayout = new javax.swing.GroupLayout(Kanban);
        Kanban.setLayout(KanbanLayout);
        KanbanLayout.setHorizontalGroup(
            KanbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KanbanLayout.createSequentialGroup()
                .addContainerGap(973, Short.MAX_VALUE)
                .addComponent(AddTaskEventButton)
                .addGap(29, 29, 29))
        );
        KanbanLayout.setVerticalGroup(
            KanbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KanbanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(AddTaskEventButton)
                .addContainerGap(591, Short.MAX_VALUE))
        );

        ContentPanel.addTab("Kanban", Kanban);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(SideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPanel))
            .addComponent(TopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(TopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1553, 1553, 1553))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTxtActionPerformed

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
        if (profileClickListener != null) {
            profileClickListener.onProfileClick();
        }
    }//GEN-LAST:event_ProfileMouseClicked

    private void AddTaskEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskEventButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTaskEventButtonActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        new AddProjectPanel().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskEventButton;
    private javax.swing.JTabbedPane ContentPanel;
    private javax.swing.JPanel Kalender;
    private javax.swing.JPanel Kanban;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Profile;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JPanel SideBarPanel;
    private javax.swing.JPanel TopBarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel projectPanel;
    // End of variables declaration//GEN-END:variables
}
