/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

/**
 *
 * @author Joy
 */
public class KanbanTask extends javax.swing.JPanel
{

    private String Status = "Pending";

    /**
     * Creates new form KanbanTask
     */
    public KanbanTask()
    {
        initComponents();
    }

    public void setTaskData(String projectName, String description, String prioritas)
    {
        title.setText(projectName);
        desc.setText(description);
        java.awt.Color warnaPrioritas = java.awt.Color.GRAY;
        switch (prioritas)
        {
            case "High":
                warnaPrioritas = java.awt.Color.RED;
                break;

            case "Medium":
                warnaPrioritas = java.awt.Color.YELLOW;
                break;

            case "Low":
                warnaPrioritas = java.awt.Color.GREEN;
                break;
        }
        Prioritas.setBackground(warnaPrioritas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        roundedPanel1 = new Component.RoundedPanel();
        title = new javax.swing.JLabel();
        desc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Prioritas = new Component.RoundedPanel();
        created = new javax.swing.JLabel();
        dueDate = new javax.swing.JLabel();
        btnMove = new Component.RoundedPanel();
        moveCombo = new javax.swing.JComboBox<>();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setRequestFocusEnabled(false);
        jScrollPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rhoncus porttitor nisl, ut rhoncus sapien congue vitae. Suspendisse porttitor sed nibh sed vehicula. Fusce placerat velit sem, non placerat lectus finibus et. Praesent dapibus ligula in consequat finibus. Integer blandit lorem sit amet efficitur egestas. Sed sed mauris sit amet leo sodales iaculis quis a est. Etiam et erat erat.\nProin vitae elit at eros porttitor feugiat sit amet nec tortor. Nam lorem dolor, elementum vitae matt");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretPosition(0);
        jTextArea1.setOpaque(false);
        jTextArea1.setRequestFocusEnabled(false);
        jTextArea1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(255, 255, 255));

        roundedPanel1.setBackground(new java.awt.Color(204, 204, 204));

        title.setBackground(new java.awt.Color(0, 0, 0));
        title.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Card Title");

        desc.setEditable(false);
        desc.setBackground(new java.awt.Color(204, 204, 204));
        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        desc.setForeground(new java.awt.Color(0, 0, 0));
        desc.setLineWrap(true);
        desc.setRows(5);
        desc.setText("Card Description");
        desc.setWrapStyleWord(true);
        desc.setBorder(null);
        desc.setOpaque(false);
        desc.setRequestFocusEnabled(false);
        desc.setSelectionColor(new java.awt.Color(255, 255, 255));
        desc.setVerifyInputWhenFocusTarget(false);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));

        Prioritas.setRadius(100);

        javax.swing.GroupLayout PrioritasLayout = new javax.swing.GroupLayout(Prioritas);
        Prioritas.setLayout(PrioritasLayout);
        PrioritasLayout.setHorizontalGroup(
            PrioritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );
        PrioritasLayout.setVerticalGroup(
            PrioritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        created.setForeground(new java.awt.Color(0, 0, 0));
        created.setText("Created By : ");

        dueDate.setForeground(new java.awt.Color(0, 0, 0));
        dueDate.setText("Due Date : ");

        btnMove.setBackground(new java.awt.Color(255, 153, 0));
        btnMove.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnMoveMouseClicked(evt);
            }
        });

        moveCombo.setBackground(new java.awt.Color(255, 153, 0));
        moveCombo.setForeground(new java.awt.Color(255, 255, 255));
        moveCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "On Progress", "Done" }));
        moveCombo.setBorder(null);
        moveCombo.addActionListener(this::moveComboActionPerformed);

        javax.swing.GroupLayout btnMoveLayout = new javax.swing.GroupLayout(btnMove);
        btnMove.setLayout(btnMoveLayout);
        btnMoveLayout.setHorizontalGroup(
            btnMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMoveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(moveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnMoveLayout.setVerticalGroup(
            btnMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(moveCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Prioritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(created)
                        .addGap(71, 71, 71)
                        .addComponent(dueDate)))
                .addContainerGap())
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(title))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prioritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(created)
                    .addComponent(dueDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoveMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnMoveMouseClicked
    {//GEN-HEADEREND:event_btnMoveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoveMouseClicked

    private void moveComboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_moveComboActionPerformed
    {//GEN-HEADEREND:event_moveComboActionPerformed
        // TODO add your handling code here:
        String statusChoose = moveCombo.getSelectedItem().toString();

        KanbanCard mainBoard = (KanbanCard) javax.swing.SwingUtilities.getAncestorOfClass(
         KanbanCard.class,
         this);

        if (mainBoard != null)
        {
            java.awt.Container wadahLama = this.getParent();
            javax.swing.JPanel wadahTarget = null;

            switch (statusChoose)
            {
                case "Pending":
                    wadahTarget = mainBoard.getWadahPending();
                    break;
                case "On Progress":
                    wadahTarget = mainBoard.getWadahInProgress();
                    break;

                case "Done":
                    wadahTarget = mainBoard.getWadahDone();
                    break;
            }
            if (wadahTarget != null && wadahTarget != wadahLama)
            {
                wadahLama.remove(this);
                wadahTarget.add(this);

                wadahLama.revalidate();
                wadahLama.repaint();
                wadahTarget.revalidate();
                wadahTarget.repaint();
            }
        }
    }//GEN-LAST:event_moveComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Component.RoundedPanel Prioritas;
    private Component.RoundedPanel btnMove;
    private javax.swing.JLabel created;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel dueDate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> moveCombo;
    private Component.RoundedPanel roundedPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
