/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import control.ProjectControl;
import control.SessionControl;
import control.TaskControl;
import exception.database.DatabaseException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import model.Project;
import model.Task;
import model.enums.TaskStatus;
import utility.event.ProjectEventBus;
import utility.security.Log;
import view.panel.component.TaskCard;

/**
 *
 * @author Joy
 */
public class KanbanPanel extends javax.swing.JPanel implements interfaces.IProjectObserver {
//    private String title;

    private TaskStatus status = TaskStatus.DONE;
    private final SessionControl sessionControl = new SessionControl();
    private final ProjectControl projectControl = new ProjectControl(sessionControl.getCurrentUser());
//    public 
    /**
     * Creates new form KanbanCard
     */

    private final TaskControl taskControl = new TaskControl();

    public KanbanPanel() {
        initComponents();
        refreshLater();
    }

    public KanbanPanel(TaskStatus t) {
        status = t;
        initComponents();
        refreshLater();

    }

    private void refreshLater() {
        SwingUtilities.invokeLater(this::showTasks);
    }

    /**
     * Reloads this Kanban column safely.
     * Handles empty selection, deleted project, and empty task list.
     */
    public final void showTasks() {
        panelItem.removeAll();

        try {
            Project selected = projectControl.resolveSelectedProject();
            if (selected == null) {
                panelItem.add(new JLabel("No project selected."));
                revalidate();
                repaint();
                return;
            }

            List<Task> list = taskControl.findByProject(selected.getId());
            if (list == null || list.isEmpty()) {
                panelItem.add(new JLabel("No tasks."));
                revalidate();
                repaint();
                return;
            }

            for (Task t : list) {
                if (t != null && t.getStatus() == status) {
                    panelItem.add(new TaskCard(t));
                }
            }
        } catch (DatabaseException | RuntimeException e) {
            Log.err(e.getMessage());
            panelItem.removeAll();
            panelItem.add(new JLabel("Failed to load tasks."));
        }
        revalidate();
        repaint();
    }



    @Override
    public void onProjectAdded(Project project) {
        if (project != null) {
            projectControl.setSelected(project);
        }
        SwingUtilities.invokeLater(this::showTasks);
    }

    @Override
    public void onProjectUpdated(Project project) {
        SwingUtilities.invokeLater(this::showTasks);
    }

    @Override
    public void onProjectDeleted(int projectId) {
        SwingUtilities.invokeLater(this::showTasks);
    }

    @Override
    public void addNotify() {
        super.addNotify();
        ProjectEventBus.getInstance().subscribe(this);
    }

    @Override
    public void removeNotify() {
        ProjectEventBus.getInstance().unsubscribe(this);
        super.removeNotify();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelItem = new javax.swing.JPanel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(272, 850));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(status.name());
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 30));
        add(jLabel2);

        panelItem.setBackground(new java.awt.Color(153, 255, 102));
        panelItem.setAlignmentX(0.5F);
        panelItem.setMaximumSize(new java.awt.Dimension(250, 800));
        panelItem.setMinimumSize(new java.awt.Dimension(250, 800));
        panelItem.setOpaque(false);
        panelItem.setPreferredSize(new java.awt.Dimension(250, 800));
        panelItem.setLayout(new javax.swing.BoxLayout(panelItem, javax.swing.BoxLayout.Y_AXIS));
        add(panelItem);
    }// </editor-fold>//GEN-END:initComponents

//    public javax.swing.JPanel getWadahInProgress()
//    {
//        return onProgresItem;
//    }
//    
//    public javax.swing.JPanel getWadahPending()
//    {
//        return panelItem;
//    }
//    
//    public javax.swing.JPanel getWadahDone()
//    {
//        return doneItem;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelItem;
    // End of variables declaration//GEN-END:variables
}
