/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import model.Project;

/**
 *
 * @author farel
 */
public class ProjectTab extends javax.swing.JPanel {

    /**
     * Creates new form ProjectTab
     */
    public ProjectTab() {
        initComponents();
    }
    public ProjectTab(Project p) {
        initComponents();
        jLabel1.setText(p.getName());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(200, 25));
        setPreferredSize(new java.awt.Dimension(200, 25));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Project");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 16));
        add(jLabel1);

        jButton1.setText("Edit");
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
