/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import java.awt.Color;
import java.awt.Cursor;
import model.Project;

/**
 *
 * @author farel
 */
public class ProjectTab extends javax.swing.JPanel {

    private static final Color NORMAL_BG = new Color(245, 245, 245);
    private static final Color HOVER_BG = new Color(225, 225, 225);
    private static final Color SELECTED_BG = new Color(185, 185, 185);

    private Project project;
    private boolean selected;
    private OnSelectListener onSelectListener;

    public interface OnSelectListener {

        void onSelect(Project project);
    }

    /**
     * Creates new form ProjectTab
     */
    public ProjectTab() {
        initComponents();
        initInteraction();
    }

    public ProjectTab(Project p) {
        initComponents();
        initInteraction();
        project = p;
        jLabel1.setText(p.getName());
    }

    private void initInteraction() {
//        setOpaque(true);
//        setBackground(NORMAL_BG);
//        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
//
//        java.awt.event.MouseAdapter hoverAndSelect = new java.awt.event.MouseAdapter() {
//            @Override
//            public void mouseEntered(java.awt.event.MouseEvent e) {
//                if (!selected) {
//                    setBackground(HOVER_BG);
//                }
//            }
//
//            @Override
//            public void mouseExited(java.awt.event.MouseEvent e) {
//                if (!selected) {
//                    setBackground(NORMAL_BG);
//                }
//            }
//
//            @Override
//            public void mouseClicked(java.awt.event.MouseEvent e) {
//                if (onSelectListener != null && project != null) {
//                    onSelectListener.onSelect(project);
//                }
//            }
//        };
//
//        addMouseListener(hoverAndSelect);
//        jLabel1.addMouseListener(hoverAndSelect);
        setOpaque(true);
        setBackground(NORMAL_BG);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        this.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (onSelectListener != null && project != null) {
                    onSelectListener.onSelect(project); // Memicu setActiveProject di HomePagePanel
                }
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (!selected) {
                    setBackground(HOVER_BG);
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                if (!selected) {
                    setBackground(NORMAL_BG);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(200, 25));
        setPreferredSize(new java.awt.Dimension(200, 25));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Project");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 16));
        add(jLabel1);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new ProjectInfoPanel(project).setVisible(true);

//
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Returns the ID of the project represented by this tab. Used by
     * HomePagePanel's observer methods to locate the correct tab.
     */
    public int getProjectId() {
        return project != null ? project.getId() : -1;
    }

    /**
     * Updates this tab to reflect the given project's new data. Called by
     * HomePagePanel.onProjectUpdated().
     */
    public void updateProject(Project p) {
        this.project = p;
        jLabel1.setText(p.getName());
        revalidate();
        repaint();
    }

    public void setOnSelectListener(OnSelectListener listener) {
        this.onSelectListener = listener;
    }

    public void setSelectedState(boolean selected) {
        this.selected = selected;
        setBackground(selected ? SELECTED_BG : NORMAL_BG);
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
