/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

/**
 *
 * @author aldio
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

import model.enums.TaskPriority;
import view.panel.component.ComponentRenderer;

public class TabelPanel extends javax.swing.JPanel {

    /**
     * Creates new form TabelPanel
     */
    public TabelPanel() {
        initComponents();
        initCustomUI();
    }

    private void initCustomUI() {
        setPreferredSize(new Dimension(1078, 633));
        removeAll();
        setLayout(new BorderLayout());
        setBackground(Color.WHITE);

        // --- PANEL ATAS ---
        JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        topPanel.setBackground(Color.WHITE);
        topPanel.setBorder(new EmptyBorder(20, 20, 10, 20));

        JButton addButton = new JButton("+ Tambah Tugas/Acara");
        addButton.setBackground(new Color(230, 50, 80));
        addButton.setForeground(Color.WHITE);
        addButton.setFocusPainted(false);
        addButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        addButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        topPanel.add(addButton);

        add(topPanel, BorderLayout.NORTH);

        String[] columns = {"Name", "Tenggat", "Tag", "Status", "Prioritas", "Aksi"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        JTable table = new JTable(model);
        table.setRowHeight(40);
        table.setBackground(Color.WHITE);
        table.setFillsViewportHeight(true);
        table.setShowVerticalLines(false);
        table.setShowHorizontalLines(true);
        table.setGridColor(new Color(240, 200, 200));

        JTableHeader header = table.getTableHeader();
        header.setBackground(Color.WHITE);
        header.setForeground(new Color(150, 0, 20));
        header.setFont(new Font("SansSerif", Font.BOLD, 14));
        header.setBorder(BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(150, 0, 20)));
        ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(JLabel.LEFT);

        DefaultTableCellRenderer paddingRenderer = new DefaultTableCellRenderer();
        paddingRenderer.setBorder(new EmptyBorder(0, 10, 0, 0));
        table.getColumnModel().getColumn(0).setCellRenderer(paddingRenderer);
        table.getColumnModel().getColumn(1).setCellRenderer(paddingRenderer);

        table.getColumnModel().getColumn(2).setCellRenderer(new ComponentRenderer(0));
        table.getColumnModel().getColumn(3).setCellRenderer(new ComponentRenderer(0));
        table.getColumnModel().getColumn(4).setCellRenderer(new ComponentRenderer(1));

        DefaultTableCellRenderer actionRenderer = new DefaultTableCellRenderer();
        actionRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(5).setCellRenderer(actionRenderer);

        table.getColumnModel().getColumn(0).setPreferredWidth(300);
        table.getColumnModel().getColumn(1).setPreferredWidth(150);
        table.getColumnModel().getColumn(5).setPreferredWidth(50);

        model.addRow(new Object[]{"name 1", "tanggal", "Kerja", "Tertunda", TaskPriority.HIGH, "..."});
        model.addRow(new Object[]{"Tugas PBO", "25 Okt 2024", "Kuliah", "Selesai", TaskPriority.MEDIUM, "..."});
        model.addRow(new Object[]{"Rapat Himaforka", "26 Okt 2024", "Organisasi", "Proses", TaskPriority.LOW, "..."});

        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setBackground(Color.WHITE);
        scrollPane.getViewport().setBackground(Color.WHITE);
        scrollPane.setBorder(BorderFactory.createEmptyBorder(0, 20, 20, 20));

        add(scrollPane, BorderLayout.CENTER);

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

//    public static void main(String[] args) {
//        try {
//            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//        // Jalankan testing panel
//        java.awt.EventQueue.invokeLater(() -> {
//            javax.swing.JFrame frame = new javax.swing.JFrame("Testing Tabel Panel");
//            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
//
//            // Masukkan TabelPanel ke dalam frame
//            TabelPanel panel = new TabelPanel();
//            frame.add(panel);
//
//            // pack() akan menyesuaikan ukuran frame mengikuti 1078x633
//            frame.pack();
//            frame.setLocationRelativeTo(null); // Tampilkan di tengah layar
//            frame.setVisible(true);
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
