/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

/**
 *
 * @author Joy
 */
public class TaskPanel extends javax.swing.JPanel
{

    /**
     * Creates new form DashboardPanel
     */
    public TaskPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectPanel = new Component.RoundedPanel();
        title = new javax.swing.JLabel();
        descScrollPane = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();

        ProjectPanel.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Project's Name");
        title.setAutoscrolls(true);

        descScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        descScrollPane.setBorder(null);
        descScrollPane.setForeground(new java.awt.Color(0, 0, 0));
        descScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        descScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        descScrollPane.setEnabled(false);
        descScrollPane.setFocusable(false);
        descScrollPane.setRequestFocusEnabled(false);
        descScrollPane.setVerifyInputWhenFocusTarget(false);
        descScrollPane.setWheelScrollingEnabled(false);

        desc.setEditable(false);
        desc.setBackground(new java.awt.Color(255, 255, 255));
        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        desc.setForeground(new java.awt.Color(0, 0, 0));
        desc.setLineWrap(true);
        desc.setRows(5);
        desc.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rhoncus porttitor nisl, ut rhoncus sapien congue vitae. Suspendisse porttitor sed nibh sed vehicula. Fusce placerat velit sem, non placerat lectus finibus et. Praesent dapibus ligula in consequat finibus. Integer blandit lorem sit amet efficitur egestas. Sed sed mauris sit amet leo sodales iaculis quis a est. Etiam et erat erat.\nProin vitae elit at eros porttitor feugiat sit amet nec tortor. Nam lorem dolor, elementum vitae matt");
        desc.setWrapStyleWord(true);
        desc.setBorder(null);
        desc.setCaretPosition(0);
        desc.setOpaque(false);
        desc.setRequestFocusEnabled(false);
        desc.setSelectionColor(new java.awt.Color(255, 255, 255));
        desc.setVerifyInputWhenFocusTarget(false);
        descScrollPane.setViewportView(desc);

        javax.swing.GroupLayout ProjectPanelLayout = new javax.swing.GroupLayout(ProjectPanel);
        ProjectPanel.setLayout(ProjectPanelLayout);
        ProjectPanelLayout.setHorizontalGroup(
            ProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        ProjectPanelLayout.setVerticalGroup(
            ProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(ProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2492, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(ProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Component.RoundedPanel ProjectPanel;
    private javax.swing.JTextArea desc;
    private javax.swing.JScrollPane descScrollPane;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
