/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel.component;

/**
 *
 * @author aldio
 */
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

import model.enums.TaskPriority;

public class ComponentRenderer extends javax.swing.JPanel implements TableCellRenderer{

    /**
     * Creates new form ComponentRenderer
     */
    private TagBite tagBite;
    private PriorityBite priorityBite;

    private int type;

    public ComponentRenderer(int type) {
        this.type = type;
        setLayout(new FlowLayout(FlowLayout.LEFT, 10, 5));
        setOpaque(true);

        if (type == 0) {
            tagBite = new TagBite();
            add(tagBite);
        } else {
            priorityBite = new PriorityBite();
            add(priorityBite);
        }
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

        setBackground(isSelected ? table.getSelectionBackground() : Color.WHITE);

        if (type == 0 && tagBite != null) {

            String text = value != null ? value.toString() : "";
            tagBite.setText(text);

            if (text.equalsIgnoreCase("Kerja") || text.equalsIgnoreCase("Kuliah")) {
                tagBite.setColor(new Color(239, 68, 68)); // Merah
            } else if (text.equalsIgnoreCase("Tertunda") || text.equalsIgnoreCase("Proses")) {
                tagBite.setColor(new Color(14, 165, 233)); // Biru
            } else if (text.equalsIgnoreCase("Selesai")) {
                tagBite.setColor(new Color(34, 197, 94)); // Hijau
            } else {
                tagBite.setColor(new Color(99, 102, 241)); // Default Ungu
            }

        } else if (type == 1 && priorityBite != null) {

            if (value instanceof TaskPriority) {
                priorityBite.setPriority((TaskPriority) value);
            } else {
                priorityBite.setPriority(TaskPriority.LOW); // Default prevent error
            }
        }

        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
