
package view.panel.component;

/**
 *
 * @author farel
 */
public class haduh extends javax.swing.JPanel {

    /**
     * Creates new form TaskCard
     */
    public haduh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tagBite1 = new view.panel.component.TagBite();
        TaskTitle = new javax.swing.JLabel();
        Tags = new javax.swing.JPanel();
        tagBite2 = new view.panel.component.TagBite();

        setBackground(new java.awt.Color(250, 250, 250));
        setMaximumSize(new java.awt.Dimension(250, 300));
        setMinimumSize(new java.awt.Dimension(250, 250));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(250, 175));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        TaskTitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        TaskTitle.setForeground(new java.awt.Color(57, 57, 57));
        TaskTitle.setText("Task Title");
        add(TaskTitle);

        Tags.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        Tags.add(tagBite2);

        add(Tags);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tags;
    private javax.swing.JLabel TaskTitle;
    private view.panel.component.TagBite tagBite1;
    private view.panel.component.TagBite tagBite2;
    // End of variables declaration//GEN-END:variables
}
