/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel.component;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import model.enums.TaskPriority;
import static model.enums.TaskPriority.*;

/**
 *
 * @author farel
 */
public class PriorityBite extends javax.swing.JPanel {

    private TaskPriority priority;

    /**
     * Creates new form Priority
     */
    public PriorityBite() {
        initComponents();
        priority = TaskPriority.MEDIUM; // Default priority
    }

    public PriorityBite(TaskPriority priority) {
        initComponents();
        this.priority = priority;
    }

    public void setPriority(TaskPriority priority) {
        this.priority = priority;
        repaint(); // Repaint to update the color based on new priority
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(100, 26));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(100, 26));

        title.setText("jLabel1");
        add(title);
    }// </editor-fold>//GEN-END:initComponents

    private void setText() {
        if (null == this.priority) {
            title.setText("LOW");
        } else // For demonstration, return a fixed color. You can modify this to return different colors based on priority level.
        {
            switch (this.priority) {
                case HIGH:
                    title.setText("HIGH");
                // return new Color(255, 102, 102); // Light red for high priority
                case MEDIUM:
                    title.setText("MEIDUM");
                default:
                    title.setText("LOW");
            }
        }
    }

    private Color getPriorityColor() {
        if (null == this.priority) {
            return new Color(102, 255, 102); // Light green for low priority
        } else // For demonstration, return a fixed color. You can modify this to return different colors based on priority level.
        {
            switch (this.priority) {
                case HIGH:
                    return new Color(255, 102, 102); // Light red for high priority
                // return new Color(255, 102, 102); // Light red for high priority
                case MEDIUM:
                    return new Color(255, 178, 102); // Light orange for medium priority
                default:
                    return new Color(102, 255, 102); // Light green for low priority
            }
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();
        int w = getWidth();
        int h = getHeight();

        // --- Pill background ---
        g2d.setColor(getPriorityColor());
        g2d.fillRoundRect(0, 0, w, h, h, h);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
