/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel.component;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author farel
 */
public class TagBite extends javax.swing.JPanel {

    private Color dotColor;
    private static final int DOT_SIZE = 10;
    private static final int DOT_GAP = 6; // gap between dot and text

    /**
     * Creates new form TagBite
     */
    public TagBite() {
        initComponents();
        this.dotColor = new Color(224, 228, 53, 100);
        setBorder(new EmptyBorder(4, 10, 4, 10));
    }

    public TagBite(String text, Color color) {
        initComponents();
        this.dotColor = color;
        setBorder(new EmptyBorder(4, 10, 4, 10)); // padding
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TagTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(new EmptyBorder(4, 10, 4, 10));
        setMaximumSize(new java.awt.Dimension(80, 22));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(50, 22));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        TagTitle.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        TagTitle.setText("jLabel1");
        TagTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(TagTitle);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();
        int w = getWidth();
        int h = getHeight();
        // Smooth rendering
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // --- Pill background ---
        g2d.setColor(setLightnessHSL(dotColor, 0.8f));
        g2d.fillRoundRect(0, 0, w, h, h, h);

        // --- Pill border ---
        g2d.setColor(setLightnessHSL(dotColor, 0.9f));
        g2d.setStroke(new BasicStroke(0.5f));
        g2d.drawRoundRect(0, 0, w - 1, h - 1, h, h);

        // --- Dot ---
        int dotX = 8;
        int dotY = (h - DOT_SIZE) / 2;
        g2d.setColor(dotColor);
        g2d.fillOval(dotX, dotY, DOT_SIZE, DOT_SIZE);


        g2d.dispose();

        if (TagTitle != null) {
            FontMetrics fm = TagTitle.getFontMetrics(TagTitle.getFont());
            int textX = dotX + DOT_SIZE + DOT_GAP;
            int labelW = fm.stringWidth(TagTitle.getText()) + 4;
            int labelH = fm.getHeight();
            int labelY = (h - labelH) / 2;
            TagTitle.setBounds(textX, labelY, labelW, labelH + 4); // ✅ real size
            TagTitle.setForeground(setLightnessHSL(dotColor, 0.3f));
        }
    }

    @Override
    public Dimension getPreferredSize() {
        FontMetrics fm = getFontMetrics(new Font("Segoe UI", Font.PLAIN, 12));
        int width = 8 + DOT_SIZE + DOT_GAP + fm.stringWidth(TagTitle.getText()) + 16;
        int height = 26;
        return new Dimension(width, height);
    }

    private Color setLightnessHSL(Color color, float targetLightness) {
        float r = color.getRed() / 255f;
        float g = color.getGreen() / 255f;
        float b = color.getBlue() / 255f;

        float max = Math.max(r, Math.max(g, b));
        float min = Math.min(r, Math.min(g, b));
        float delta = max - min;

        float h = 0f, s, l;
        l = (max + min) / 2f;
        s = (delta == 0) ? 0 : delta / (1 - Math.abs(2 * l - 1));

        if (delta != 0) {
            if (max == r) {
                h = ((g - b) / delta) % 6;
            } else if (max == g) {
                h = ((b - r) / delta) + 2;
            } else {
                h = ((r - g) / delta) + 4;
            }
            h /= 6f;
            if (h < 0) {
                h += 1f;
            }
        }

        l = Math.max(0f, Math.min(1f, targetLightness));

        float c = (1 - Math.abs(2 * l - 1)) * s;
        float x = c * (1 - Math.abs((h * 6) % 2 - 1));
        float m = l - c / 2;

        float r1, g1, b1;
        switch ((int) (h * 6)) {
            case 0:
                r1 = c;
                g1 = x;
                b1 = 0;
                break;
            case 1:
                r1 = x;
                g1 = c;
                b1 = 0;
                break;
            case 2:
                r1 = 0;
                g1 = c;
                b1 = x;
                break;
            case 3:
                r1 = 0;
                g1 = x;
                b1 = c;
                break;
            case 4:
                r1 = x;
                g1 = 0;
                b1 = c;
                break;
            default:
                r1 = c;
                g1 = 0;
                b1 = x;
                break;
        }

        return new Color(
                Math.min(1f, r1 + m),
                Math.min(1f, g1 + m),
                Math.min(1f, b1 + m)
        );
    }

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("TagBite Preview");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            
            javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 12));
            panel.setBackground(new Color(245, 245, 250));
            panel.setBorder(new EmptyBorder(8, 8, 8, 8));
            
            panel.add(new TagBite("Design", new Color(99, 102, 241)));
            panel.add(new TagBite("Urgent", new Color(239, 68, 68)));
            panel.add(new TagBite("In Review", new Color(245, 158, 11)));
            panel.add(new TagBite("Done", new Color(34, 197, 94)));
            panel.add(new TagBite("Backend", new Color(14, 165, 233)));
            
            frame.setContentPane(panel);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TagTitle;
    // End of variables declaration//GEN-END:variables
}
