/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel.component;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.border.EmptyBorder;
import model.Tag;
import model.Task;
import view.*;



/**
 *
 * @author farel
 */
public class TaskCard extends javax.swing.JPanel {
    private Task task = new Task();
    /**
     * Creates new form TaskCard
     */
    public TaskCard() {
        initComponents();
        setBorder(new EmptyBorder(10, 10, 10, 10));
    }
    private void addTag(Tag t){
        Tags.add(new TagBite(t.getName(), new Color(230, 230, 56)));
    }
    public void setTask(Task t) {
        task = (t != null) ? t : new Task();

        if (jLabel1 != null) {
            jLabel1.setText(task.getTitle() != null ? task.getTitle() : "Untitled Task");
        }
        if (Description != null) {
            Description.setText(task.getDescription() != null ? task.getDescription() : "No description");
        }
        if (tagBite2 != null) {
            tagBite2.setText(task.getTitle() != null ? task.getTitle() : "Task");
        }
        priorityBite2.setPriority(t.getPriority());
        for(Tag tag: task.getTags()){
            addTag(tag);
        }
        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        Tags = new javax.swing.JPanel();
        tagBite2 = new view.panel.component.TagBite();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        priorityBite2 = new view.panel.component.PriorityBite();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)

        );
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(task.getTitle());
        jLabel1.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabel1, gridBagConstraints);

        Tags.setOpaque(false);
        Tags.setRequestFocusEnabled(false);
        Tags.setLayout(new javax.swing.BoxLayout(Tags, javax.swing.BoxLayout.X_AXIS));
        Tags.add(tagBite2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(Tags, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(234, 86));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setOpaque(false);

        Description.setEditable(false);
        Description.setBackground(new java.awt.Color(204, 204, 0));
        Description.setColumns(20);
        Description.setRows(5);
        Description.setAutoscrolls(false);
        Description.setEnabled(false);
        Description.setMaximumSize(new java.awt.Dimension(232, 84));
        Description.setOpaque(false);
        jScrollPane1.setViewportView(Description);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        add(jScrollPane1, gridBagConstraints);

        jPanel2.setOpaque(false);
        jPanel2.add(priorityBite2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(jPanel2, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        add(jComboBox1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setText("Due");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(jLabel3, gridBagConstraints);

        jLabel2.setText(task.getDueDate().toString());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        try {
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            int w = getWidth();
            int h = getHeight();
            int arc = 24;
            // background
            g2.setColor(new Color(0xFA, 0xFA, 0xFA));
            g2.fillRoundRect(0, 0, w, h, arc, arc);
            // border
            g2.setColor(new Color(200, 200, 200));
            g2.drawRoundRect(0, 0, w - 1, h - 1, arc, arc);
        } finally {
            g2.dispose();
        }
        super.paintComponent(g);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Description;
    private javax.swing.JPanel Tags;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private view.panel.component.PriorityBite priorityBite2;
    private view.panel.component.TagBite tagBite2;
    // End of variables declaration//GEN-END:variables
}
