/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel.component;

import model.Task;

/**
 *
 * @author farel
 */
public class TaskCard extends javax.swing.JPanel {
    private Task task = new Task();
    /**
     * Creates new form TaskCard
     */
    public TaskCard() {
        initComponents();
    }
    
    public void setTask(Task t){
        task = t;
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Tags = new javax.swing.JPanel();
        tagBite2 = new view.panel.component.TagBite();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        priorityBite2 = new view.panel.component.PriorityBite();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)

        );
        jLabel1.setText(task.getTitle());
        jLabel1.setAlignmentX(0.5F);
        add(jLabel1);

        Tags.setLayout(new javax.swing.BoxLayout(Tags, javax.swing.BoxLayout.X_AXIS));
        Tags.add(tagBite2);

        add(Tags);

        Description.setColumns(20);
        Description.setRows(5);
        Description.setEnabled(false);
        jScrollPane1.setViewportView(Description);

        add(jScrollPane1);
        add(priorityBite2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Description;
    private javax.swing.JPanel Tags;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private view.panel.component.PriorityBite priorityBite2;
    private view.panel.component.TagBite tagBite2;
    // End of variables declaration//GEN-END:variables
}
