/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panel;

import model.Project;
import java.text.SimpleDateFormat;

/**
 *
 * @author Silvanus
 */
public class ProjectInfoPanel extends javax.swing.JFrame {

     private Project project;
    
    /**
     * Creates new form ProjectInfoPanel
     */
    public ProjectInfoPanel() {
        initComponents();
        
        this.project = project;
        loadProjectData();
    }
    
    private void loadProjectData() {
        if (project == null) return;

        //untuk show nama & deskripsi Project
        ProjectNameLabel.setText(project.getName());
        DescriptionTextAre.setText(project.getDescription());
        
        //untuk show Created At
        SimpleDateFormat formatter = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        CreatedAtDateLabel.setText(formatter.format(project.getCreatedAt()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectInfoPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        ProjectIconLabel = new javax.swing.JLabel();
        ProjectNameLabel = new javax.swing.JLabel();
        MoreIconLabel = new javax.swing.JLabel();
        CancelIconLabel = new javax.swing.JLabel();
        DescriptionPanel = new javax.swing.JPanel();
        DescriptionScrollPane = new javax.swing.JScrollPane();
        DescriptionTextAre = new javax.swing.JTextArea();
        CreatedAtPanel = new javax.swing.JPanel();
        CreatedAtLabel = new javax.swing.JLabel();
        CreatedAtDateLabel = new javax.swing.JLabel();
        OwnerPanel = new javax.swing.JPanel();
        OwnerLabel = new javax.swing.JLabel();
        OwnerProfilePictureLabel = new javax.swing.JLabel();
        MemberPanel = new javax.swing.JPanel();
        MemberLabel = new javax.swing.JLabel();
        MemberProfilePictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProjectInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        TopPanel.setBackground(new java.awt.Color(255, 255, 255));

        ProjectIconLabel.setForeground(new java.awt.Color(255, 0, 0));
        ProjectIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProjectIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/project_panel/file_icon.png"))); // NOI18N
        ProjectIconLabel.setToolTipText("");

        ProjectNameLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ProjectNameLabel.setText("Project_Name");

        MoreIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MoreIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/project_panel/menu_icon.png"))); // NOI18N

        CancelIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/project_panel/x_icon.png"))); // NOI18N

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProjectNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoreIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MoreIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        DescriptionPanel.setBackground(new java.awt.Color(255, 255, 255));
        DescriptionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescriptionPanelMouseClicked(evt);
            }
        });

        DescriptionTextAre.setColumns(20);
        DescriptionTextAre.setRows(5);
        DescriptionTextAre.setText("yeah");
        DescriptionScrollPane.setViewportView(DescriptionTextAre);

        javax.swing.GroupLayout DescriptionPanelLayout = new javax.swing.GroupLayout(DescriptionPanel);
        DescriptionPanel.setLayout(DescriptionPanelLayout);
        DescriptionPanelLayout.setHorizontalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DescriptionScrollPane)
                .addContainerGap())
        );
        DescriptionPanelLayout.setVerticalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DescriptionPanelLayout.createSequentialGroup()
                .addComponent(DescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        CreatedAtPanel.setBackground(new java.awt.Color(255, 255, 255));

        CreatedAtLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CreatedAtLabel.setText("Created At");

        CreatedAtDateLabel.setText("[DATE]");

        javax.swing.GroupLayout CreatedAtPanelLayout = new javax.swing.GroupLayout(CreatedAtPanel);
        CreatedAtPanel.setLayout(CreatedAtPanelLayout);
        CreatedAtPanelLayout.setHorizontalGroup(
            CreatedAtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatedAtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreatedAtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreatedAtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreatedAtDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        CreatedAtPanelLayout.setVerticalGroup(
            CreatedAtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatedAtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreatedAtLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreatedAtDateLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        OwnerPanel.setBackground(new java.awt.Color(255, 255, 255));

        OwnerLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        OwnerLabel.setText("Owner");

        OwnerProfilePictureLabel.setText("profile_pic");

        javax.swing.GroupLayout OwnerPanelLayout = new javax.swing.GroupLayout(OwnerPanel);
        OwnerPanel.setLayout(OwnerPanelLayout);
        OwnerPanelLayout.setHorizontalGroup(
            OwnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OwnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OwnerProfilePictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OwnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OwnerPanelLayout.setVerticalGroup(
            OwnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OwnerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OwnerProfilePictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        MemberPanel.setBackground(new java.awt.Color(255, 255, 255));

        MemberLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MemberLabel.setText("Member");

        MemberProfilePictureLabel.setText("member_pic");

        javax.swing.GroupLayout MemberPanelLayout = new javax.swing.GroupLayout(MemberPanel);
        MemberPanel.setLayout(MemberPanelLayout);
        MemberPanelLayout.setHorizontalGroup(
            MemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MemberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemberProfilePictureLabel))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        MemberPanelLayout.setVerticalGroup(
            MemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberPanelLayout.createSequentialGroup()
                .addComponent(MemberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberProfilePictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ProjectInfoPanelLayout = new javax.swing.GroupLayout(ProjectInfoPanel);
        ProjectInfoPanel.setLayout(ProjectInfoPanelLayout);
        ProjectInfoPanelLayout.setHorizontalGroup(
            ProjectInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectInfoPanelLayout.createSequentialGroup()
                .addGroup(ProjectInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ProjectInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ProjectInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ProjectInfoPanelLayout.createSequentialGroup()
                                .addGroup(ProjectInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CreatedAtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OwnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(ProjectInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MemberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProjectInfoPanelLayout.setVerticalGroup(
            ProjectInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreatedAtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OwnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MemberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescriptionPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescriptionPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectInfoPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CancelIconLabel;
    private javax.swing.JLabel CreatedAtDateLabel;
    private javax.swing.JLabel CreatedAtLabel;
    private javax.swing.JPanel CreatedAtPanel;
    private javax.swing.JPanel DescriptionPanel;
    private javax.swing.JScrollPane DescriptionScrollPane;
    private javax.swing.JTextArea DescriptionTextAre;
    private javax.swing.JLabel MemberLabel;
    private javax.swing.JPanel MemberPanel;
    private javax.swing.JLabel MemberProfilePictureLabel;
    private javax.swing.JLabel MoreIconLabel;
    private javax.swing.JLabel OwnerLabel;
    private javax.swing.JPanel OwnerPanel;
    private javax.swing.JLabel OwnerProfilePictureLabel;
    private javax.swing.JLabel ProjectIconLabel;
    private javax.swing.JPanel ProjectInfoPanel;
    private javax.swing.JLabel ProjectNameLabel;
    private javax.swing.JPanel TopPanel;
    // End of variables declaration//GEN-END:variables
}
